### ISSUE TITLE
Lipsync Converter: Index out of range exception

### ISSUE THREAD

**Issue by maxton** [maxton/LibForge#20]
The cause of errors on many customs.

e.g. "Back in Black - ACDC", "Hells Bells - ACDC", "Black Smoke Rising - Greta Van Fleet" to name a few

**Comment by PikminGuts92** [comment]
I forgot to take into account that the various lipsync files can have different frame counts within the same song.

**Comment by maxton** [comment]
Fixed by #25. Thanks @PikminGuts92
