### ISSUE TITLE
Maximum size of multi-song pkg

### ISSUE THREAD

**Issue by Blackened15** [maxton/LibForge#32]
After hitting the entitlement limit on PS4 for RB4 (2500, so 2500 pkg limit), decided to try again and make multi-song pkg. After testing, it seems the game has a size limit on what it can load via a single pkg file. That limit is around 100mb. (Around 100mb of CON file before conversion seems to work fine, even if the resulting pkg is a bit bigger)

If you go over the limit, the game will get stuck forever on "finding additional content". 

If you manage to get just one song above the size limit, the game will load the content, but won't be able to load the song to play, the data seems to be out of range of what the game can read.

Ex: Make a 2 pack with a 90mb song and a 70 mb song, it will find the songs, let you play whichever was packed first, but the 2nd one will not play the preview and will crash when you start it.

Not quite an issue, but I couldn't find another spot to report this.

**Comment by maxton** [comment]
Yes, it seems that Harmonix doesn't release multi-song DLC packages on PS4, but rather when someone buys a pack, they're simply entitled to all the individual packages. I think that it's reasonable to use a 1-song-per-pkg limit by default, and allow the user to override this if they want the risk.

This could also just be a bug with LibOrbisPkg doing something invalid with big PKGs. I'll have to check on that.
