### ISSUE TITLE
How Can I convert all Con files in a directory ?

### ISSUE THREAD

**Issue by AbDoOdOo** [maxton/LibForge#33]
![Screenshot (38)](https://user-images.githubusercontent.com/1081803/64447521-39104800-d0e4-11e9-9fa6-2e7392abc252.png)

Help please 
Thanks

**Comment by maxton** [comment]
ForgeTool can convert all Con files in a directory. I think the issue here is that one of your CONs isn't playing nice with the converter. Try to figure out which one is throwing that error (e.g. through a binary search)
