### ISSUE TITLE
incorrect time calculation when in overdrive

### ISSUE THREAD

**Issue by LlysiX** [maxton/LibForge#35]
For making my large clone hero setlist playable in rock band 4/3/2, I have used the program Onyx (Onyxite Customs) to convert the clone hero song folders into RB3CON format for use in RB3 and to convert to RB4 .pkgs via libforge. In RB3, these songs show correct timings (same as clone hero) when activating overdrive, but when those songs are converted to RB4, they end up having the overdrive chip down in odd increments and causing the time in overdrive to be much shorter/nearly halved compared to in RB3.

this is the same overdrive phrases on both games
RB4:
![od (1)](https://user-images.githubusercontent.com/79173634/108136684-56826900-706f-11eb-9630-e461dc538a36.gif)
RB3:
![od3](https://user-images.githubusercontent.com/79173634/108144210-15458580-707e-11eb-85aa-3e06397a24d3.gif)

**Comment by maxton** [comment]
Uh, I'm guessing Onyxite takes MIDI note off events and changes them into 0-velocity note on events to save a byte per event. I guess REAPER doesn't do this. But I think I can fix it.
